language: rust
rust:
  - nightly

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --verbose --all -- --write-mode diff
  - cargo build --verbose --all
  - cargo test --verbose --all

cache: cargo
