language: rust
rust:
  - stable
  - nightly

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --write-mode diff
  - cargo build --all
  - cargo test --all

cache: cargo
